### ISSUE TITLE
autocompletion does only work in the current directory

### ISSUE THREAD

**Issue by liquiddevelopmentnet** [gsayson/deacon#4]
(improvement)

autocompletion currently only completes filenames from the cwd, instead, it should get the already written path and resolve in that directory.

for example, if we have a folder structure like this
- folder1
  - file1
  - file2
- folder2
  - coolfile
  - coolbigrat

`folde` should complete to `folder1` or `folder2`
`folder1/fi` should complete to `folder1/file1` or `folder1/file2`
`folder2/coolb` should complete to `folder2/coolbigrat`
and so on...

**Comment by SaHHiiLL** [comment]
> `folde` should complete to `folder1` or `folder2`
> `folder1/fi` should complete to `folder1/file1` or `folder1/file2`
> `folder2/coolb` should complete to `folder2/coolbigrat`
> and so on...

it should autocomplete to the longest matching string.  
so for first example it should only complete upto `folder` and leave the rest to the user, which is the case with bash and zsh
- `folde` should complete to `folder`
- `folder1/fi` should complete to `folder1/file`
- `folder2/coolb` should complete to `folder2/coolbigrat`
- and so on...

**Comment by gsayson** [comment]
It also works with `~`.
It can autocomplete from any directory.

Looks like there's no problem on Windows, I'm not sure about UNIX where the separator is the `/` character.
I'll close this issue for now; if there's still an issue, please re-open this issue.
